name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check reo code
        uses: actions/checkout@v3
      - name: Install pytest
        run: |
          echo Install pytest...
          pip install -U pytest
          pip install nltk
          echo done.
      - name: Run tests
        run: |
          echo Run tests...
          pytest
          echo done.
